nodeLinker: node-modules

supportedArchitectures:
  cpu:
    - x64
    - arm64
    - x86
  libc:
    - glibc
    - musl
  os:
    - linux
    - darwin
    - win32

yarnPath: .yarn/releases/yarn-4.7.0.cjs
