import 'scripts/clientSideRedirection.js';
import 'scripts/app.module.js';
import 'scripts/app.config.js';
import 'scripts/app.run.js';
import 'scripts/app_enforceAuth.js';

// components
import 'scripts/components/FormStatusModal/FormStatusModal';
import 'scripts/components/FormStatusPopover/FormStatusPopover_angular';
import 'scripts/components/GoogleLogin/GoogleLogin';
import 'scripts/components/ExportModal/ExportModal';

// React components
import 'scripts/components/JournalUploadPage/JournalUploadPage_angular';
import 'scripts/components/PromoUploadPage/PromoUploadPage_angular';

// Controllers
import 'scripts/controllers/angularUiTreeConfig.js';
import 'features/accessEvent/accessEvent.controller.js';
import 'features/activatePermission/activatePermission.controller.js';
import 'features/cloneEvent/cloneEvent.controller.js';
import 'features/editRegistrationModal/editRegistrationModal.controller.js';
import 'features/eventDashboard/eventDashboard.controller.js';
import 'features/eventDetails/eventDetails.controller.js';
import 'features/eventForm/eventForm.controller.js';
import 'features/eventOverview/eventOverview.controller.js';
import 'features/eventPermissions/eventPermissions.controller.js';
import 'features/eventRegistrations/eventRegistrations.controller.js';
import 'features/globalPromotions/globalPromotions.controller.ts';
import 'features/help/help.controller.js';
import 'features/oktaDescription/oktaDescription.controller.js';
import 'features/landing/landing.controller.js';
import 'features/paymentApproval/paymentApproval.controller.js';
import 'features/paymentModal/paymentModal.controller.js';
import 'features/registration/registration.controller.js';
import 'features/registrationModal/registrationModal.controller.js';
import 'features/reviewRegistration/reviewRegistration.controller.js';
import 'features/paymentCashCheckReport/paymentCashCheckReport.controller.js';
import 'features/journalUploadReview/journalUploadReview.controller.js';

// Directives
import 'scripts/directives/adminNav/adminNav.js';
import 'scripts/directives/autoFocus/autoFocus.js';
import 'scripts/directives/blockEditor/blockEditor.js';
import 'scripts/directives/blockRegistration/blockRegistration.js';
import 'scripts/directives/blocks/blocks.js';
import 'scripts/directives/datepicker/datepicker.js';
import 'scripts/directives/questionToolbar/questionToolbar.js';
import 'scripts/directives/ngEnter/ngEnter.js';
import 'scripts/directives/page/page.js';
import 'scripts/directives/payment/payment.js';
import 'scripts/directives/pickadate/pickadate.js';
import 'scripts/directives/promotion/promotion.ts';
import 'scripts/directives/registrationTypeSelect/registrationTypeSelect.js';
import 'scripts/directives/selectOnClick/selectOnClick.js';
import 'scripts/directives/showAnswer/showAnswer.js';
import 'scripts/directives/showGroupModal/showGroupModal.js';
import 'scripts/directives/showErrors/showErrors.js';
import 'scripts/directives/stringToNumber/stringToNumber.js';
import 'scripts/directives/rule/rule.js';
import 'scripts/directives/readFile/readFile.js';

// Filters
import 'scripts/filters/evtDateFormat.js';
import 'scripts/filters/joiner.js';
import 'scripts/filters/paymentTypeFormat.js';
import 'scripts/filters/phoneFormat.js';
import 'scripts/filters/toTrustedHtml.js';
import 'scripts/filters/unique.js';
import 'scripts/filters/dateRangeFormat.js';
import 'scripts/filters/showQuestionFilter.js';
import 'scripts/filters/localizedCurrency.js';
import 'scripts/filters/eventAddressFormat.js';

// Services
import 'scripts/services/analytics.service.js';
import 'scripts/services/authorizationInterceptor.js';
import 'scripts/services/blockTagTypeService.ts';
import 'scripts/services/ConfCache.js';
import 'scripts/services/constants.js';
import 'scripts/services/currentRegistrationInterceptor.js';
import 'scripts/services/DateRangeService.js';
import 'scripts/services/error.js';
import 'scripts/services/globalPromotionService.ts';
import 'scripts/services/growlService.js';
import 'scripts/services/gtmService.js';
import 'scripts/services/httpReturnStatusInterceptor.js';
import 'scripts/services/httpUrlInterceptor.js';
import 'scripts/services/loginDialog.js';
import 'scripts/services/logout.js';
import 'scripts/services/MinistriesCache.ts';
import 'scripts/services/MinistryAdminsCache.ts';
import 'scripts/services/modalMessage.js';
import 'scripts/services/payment.js';
import 'scripts/services/PermissionCache.js';
import 'scripts/services/ProfileCache.js';
import 'scripts/services/registration.js';
import 'scripts/services/RegistrationCache.js';
import 'scripts/services/transformCampusAnswerInterceptor.js';
import 'scripts/services/unauthorizedInterceptor.js';
import 'scripts/services/uuid.js';
import 'scripts/services/validateRegistrant.js';
import 'scripts/services/validationInterceptor.js';
import 'scripts/services/paymentReportService.js';
import 'scripts/services/journalUploadService.ts';
import 'scripts/services/promoReportService.ts';
